### ISSUE TITLE
UI conflicts with Captain Busted Diablo Strike

### ISSUE THREAD

**Issue by Feathertoes** [CrazyAmphibian/captainutilityswap#1]
I figure it wouldn't be too much trouble to fix, but the ui for the [aforementioned mod](https://thunderstore.io/package/farofus/Captain_Busted_Diablo_Strike/), when working correctly, shows the number of uses available (that was put there to get around the fact it used to overlay with the countdown when you picked up a hardlight afterburner) and a countdown showing how many seconds it takes for the strike to land after calling it. When both mods are active, however, the countdown is removed in place of the keybind tip 
![image](https://github.com/CrazyAmphibian/captainutilityswap/assets/70271757/ac9c46d3-2bcc-40d5-9bd3-c62ca5448e3f)

**Comment by CrazyAmphibian** [comment]
looking at their code, they also set the text, so i'm not sure what the best approach would be (nor how to detect if the mod is enabled to enable such a compatibility patch)
i give no gaurentees that i'll look too deep into it, i'm putting my time into other things at the moment

**Comment by ureverypie** [comment]
how bout just a config thing to turn off that bit of ui? it's not really too important to always see after you've seen it the first time

**Comment by CrazyAmphibian** [comment]
yeah, adding a config would be far easier, i'll see what i can do

**Comment by CrazyAmphibian** [comment]
the option is in code, but my visual studio borked itself somehow so i'm not able to compile the mod myself right now.

Will close this issue once i make it into a release

**Comment by ureverypie** [comment]
any updates on this?
